name: Health check

on:
  schedule:
    - cron:  '0 7 * * *'

jobs:
  health_check_ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://boiling-peak-04070.herokuapp.com/health

